"""Docker mode: generate Dockerfile(s) and compose.yaml from the manifest.

``initc init --docker`` scaffolds the same starter files as local mode (the
image needs them too), skips local installs, and generates one Dockerfile per
stack plus a compose file wiring the stacks and any declared sidecar services.

Generated docker files are STARTING POINTS, owned by the project afterwards:
the same never-overwrite rule applies, so hand edits survive every re-run.
"""

from __future__ import annotations

from pathlib import Path

import yaml

from init_configurator import local_mode
from init_configurator.beacons import PrimaryChoice
from init_configurator.languages import provider_for
from init_configurator.manifest import DockerConfig, Manifest, Stack

GENERATED_HEADER = (
    "# Generated by init-configurator from project.yaml - edit freely;\n"
    "# init never overwrites an existing file, so your changes stick.\n"
)

DOCKERIGNORE = """\
.git
.venv
node_modules
__pycache__
dist
.env
"""


def initialize(manifest: Manifest, root: Path, *, agent: PrimaryChoice = "agents") -> list[str]:
    """Docker mode = the local scaffold (without installs) + generated docker files."""
    report = local_mode.initialize(manifest, root, skip_install=True, agent=agent)
    report.extend(local_mode.write_missing(root, docker_files(manifest)))
    return report


def docker_files(manifest: Manifest) -> dict[str, str]:
    """Everything docker mode MAY create, keyed by root-relative path."""
    files: dict[str, str] = {".dockerignore": DOCKERIGNORE}
    for stack in manifest.stacks:
        prefix = "" if stack.root == "." else f"{stack.root.rstrip('/')}/"
        files[f"{prefix}Dockerfile"] = _dockerfile(stack)
    config = manifest.docker or DockerConfig()
    if config.compose:
        files["compose.yaml"] = _compose(manifest, config)
    return files


def _dockerfile(stack: Stack) -> str:
    """Header + the language's body + a CMD taken from the manifest."""
    body = provider_for(stack.language).dockerfile_body(stack)
    return f"{GENERATED_HEADER}{body}{_cmd_line(stack)}"


def _cmd_line(stack: Stack) -> str:
    """CMD from the manifest's start/dev task, or a pointer when none exists."""
    command = stack.tasks.get("start") or stack.tasks.get("dev")
    if command is None:
        return (
            "\n# No 'start' or 'dev' task in project.yaml - add one there, or write:\n"
            '# CMD ["sh", "-c", "<your start command>"]\n'
        )
    escaped = command.replace('"', '\\"')
    return f'\nCMD ["sh", "-c", "{escaped}"]\n'


def _compose(manifest: Manifest, config: DockerConfig) -> str:
    services: dict[str, dict[str, object]] = {}
    for stack in manifest.stacks:
        service: dict[str, object] = {"build": {"context": stack.root}}
        if manifest.env:
            service["env_file"] = [".env"]
        services[stack.name] = service
    for image in config.services:
        services[image.split(":")[0]] = {"image": image}
    return GENERATED_HEADER + yaml.safe_dump({"services": services}, sort_keys=False)
