"""Docker mode: generate Dockerfile(s) and compose.yaml from the manifest.

``initc init --docker`` scaffolds the same starter files as local mode (the
image needs them too), skips local installs, and generates one Dockerfile per
stack plus a compose file wiring the stacks and any declared sidecar services.

Generated docker files are STARTING POINTS, owned by the project afterwards:
the same never-overwrite rule applies, so hand edits survive every re-run.
"""

from __future__ import annotations

from pathlib import Path

import yaml

from init_configurator import local_mode
from init_configurator.beacons import PrimaryChoice
from init_configurator.manifest import DockerConfig, Manifest, Stack

GENERATED_HEADER = (
    "# Generated by init-configurator from project.yaml - edit freely;\n"
    "# init never overwrites an existing file, so your changes stick.\n"
)

DOCKERIGNORE = """\
.git
.venv
node_modules
__pycache__
dist
.env
"""


def initialize(manifest: Manifest, root: Path, *, agent: PrimaryChoice = "agents") -> list[str]:
    """Docker mode = the local scaffold (without installs) + generated docker files."""
    report = local_mode.initialize(manifest, root, skip_install=True, agent=agent)
    report.extend(local_mode.write_missing(root, docker_files(manifest)))
    return report


def docker_files(manifest: Manifest) -> dict[str, str]:
    """Everything docker mode MAY create, keyed by root-relative path."""
    files: dict[str, str] = {".dockerignore": DOCKERIGNORE}
    for stack in manifest.stacks:
        prefix = "" if stack.root == "." else f"{stack.root.rstrip('/')}/"
        files[f"{prefix}Dockerfile"] = _dockerfile(stack)
    config = manifest.docker or DockerConfig()
    if config.compose:
        files["compose.yaml"] = _compose(manifest, config)
    return files


def _dockerfile(stack: Stack) -> str:
    if stack.language == "python":
        body = _python_uv_body(stack) if stack.package_manager == "uv" else _python_pip_body(stack)
    else:
        body = _node_body(stack)
    return f"{GENERATED_HEADER}{body}{_cmd_line(stack)}"


def _python_uv_body(stack: Stack) -> str:
    # Paths inside the image are fine by definition - only host paths break clones.
    uv_copy = "COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv"  # path-lint: ignore
    return f"""\
FROM python:{stack.version}-slim
{uv_copy}
WORKDIR /app

# Dependencies first, project second - keeps the dependency layer cached
# across source-only changes.
COPY pyproject.toml uv.lock* ./
RUN uv sync --no-dev --no-install-project
COPY . .
RUN uv sync --no-dev
"""


def _python_pip_body(stack: Stack) -> str:
    requirement_files = [f for f in stack.dependency_files if f != "pyproject.toml"]
    lines = [f"FROM python:{stack.version}-slim", "WORKDIR /app", ""]
    for requirement_file in requirement_files:
        lines.append(f"COPY {requirement_file} ./")
        lines.append(f"RUN pip install --no-cache-dir -r {requirement_file}")
    lines.append("COPY . .")
    if "pyproject.toml" in stack.dependency_files:
        lines.append("RUN pip install --no-cache-dir .")
    return "\n".join(lines) + "\n"


def _node_body(stack: Stack) -> str:
    corepack = "RUN corepack enable\n" if stack.package_manager == "pnpm" else ""
    lockfile = "pnpm-lock.yaml*" if stack.package_manager == "pnpm" else "package-lock.json*"
    return f"""\
FROM node:{stack.version}-slim
{corepack}WORKDIR /app

COPY package.json {lockfile} ./
RUN {stack.package_manager} install
COPY . .
"""


def _cmd_line(stack: Stack) -> str:
    """CMD from the manifest's start/dev task, or a pointer when none exists."""
    command = stack.tasks.get("start") or stack.tasks.get("dev")
    if command is None:
        return (
            "\n# No 'start' or 'dev' task in project.yaml - add one there, or write:\n"
            '# CMD ["sh", "-c", "<your start command>"]\n'
        )
    escaped = command.replace('"', '\\"')
    return f'\nCMD ["sh", "-c", "{escaped}"]\n'


def _compose(manifest: Manifest, config: DockerConfig) -> str:
    services: dict[str, dict[str, object]] = {}
    for stack in manifest.stacks:
        service: dict[str, object] = {"build": {"context": stack.root}}
        if manifest.env:
            service["env_file"] = [".env"]
        services[stack.name] = service
    for image in config.services:
        services[image.split(":")[0]] = {"image": image}
    return GENERATED_HEADER + yaml.safe_dump({"services": services}, sort_keys=False)
