"""The .env contract: template ``.env.example`` from the manifest's env list.

The generated file is a build artifact — the header says so. Anyone needing a
new variable adds it to project.yaml and re-runs ``initc env``; doctor (a later
phase) diffs the two to catch drift in either direction. Secret vars get a
blank value so real credentials can never leak through an example file.
"""

from pathlib import Path

from init_configurator.manifest import Manifest

ENV_EXAMPLE_FILENAME = ".env.example"

HEADER = """\
# Generated by init-configurator from project.yaml — edit the manifest, not this file.
# Copy to .env and fill in the values; .env itself must never be committed.
"""


def render_env_example(manifest: Manifest) -> str | None:
    """Render the file content, or ``None`` when the manifest declares no vars."""
    if not manifest.env:
        return None
    blocks = [HEADER]
    for var in manifest.env:
        required = "required" if var.required else "optional"
        traits = f"{required}, secret" if var.secret else required
        comment = f"# {var.name} ({traits})"
        if var.description:
            comment += f": {var.description}"
        value = "" if var.secret else var.example
        blocks.append(f"{comment}\n{var.name}={value}")
    return "\n\n".join(blocks) + "\n"


def write_env_example(manifest: Manifest, root: Path) -> Path | None:
    """(Re)write ``.env.example`` at the project root; returns the path or ``None``."""
    content = render_env_example(manifest)
    if content is None:
        return None
    path = root / ENV_EXAMPLE_FILENAME
    path.write_text(content, encoding="utf-8")
    return path
